// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rneewcvouitgksijutvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuZWV3Y3ZvdWl0Z2tzaWp1dHZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3MDg0MTUsImV4cCI6MjA5MjI4NDQxNX0.GdHjE_yZqw-bYztnnG_gF2LLdgkqhFbVaEBjRxMmXQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});