// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stotvkliskgprouzhjqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0b3R2a2xpc2tncHJvdXpoanFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzMwMjEsImV4cCI6MjA2MTY0OTAyMX0.IwDUq2_HtmCpApUMi4CFQWN31866R0DhaiX8URJuZrY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);